package tests;// Generated by Selenium IDE

import org.junit.Test;
public class DeleteGroup extends TestBase{



  @Test
  public void groupDeleting() {
    app.getNavigationHelper().groupsOpening();
   if(! app.getGroupHelper().isThereAGroup()){
     app.getGroupHelper().createGroup(null);
   }
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
