package tests;// Generated by Selenium IDE

import appmanager.GroupData;
import org.testng.Assert;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import java.util.List;

public class DeleteGroup extends TestBase{

  @BeforeTest
  public void ensurePreconditions() {
    app.goTo().groupPage();
    if (app.group().list().size() == 0) {
      app.group().create(new GroupData().withName("test1"));
    }
  }

  @Test
  public void groupDeleting() {

    List<GroupData> before = app.group().list();
    int index = before.size() - 1;
    app.group().delete(index);
    List<GroupData> after = app.group().list();
    Assert.assertEquals(after.size() ,  before.size() - 1);
    System.out.println("Number of groups BEFORE = " + before);
    System.out.println("Number of groups AFTER = " + after);

    before.remove(index);
    Assert.assertEquals(before, after);

  }



}

