package tests;// Generated by Selenium IDE

import appmanager.GroupData;
import org.testng.Assert;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import java.util.List;

public class DeleteGroup extends TestBase{

  @BeforeTest
  public void ensurePreconditions() {
    app.getNavigationHelper().groupsOpening();
    if (!app.getGroupHelper().isThereAGroup()) {
      app.getGroupHelper().createGroup(null);
    }
  }

  @Test
  public void groupDeleting() {

    List<GroupData> before = app.getGroupHelper().getGroupList();
    app.getGroupHelper().selectGroup(before.size() - 1);
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
    List<GroupData> after = app.getGroupHelper().getGroupList();
    Assert.assertEquals(after.size() ,  before.size() - 1);
    System.out.println("Number of groups BEFORE = " + before);
    System.out.println("Number of groups AFTER = " + after);

    before.remove(before.size() - 1);
    Assert.assertEquals(before, after);

  }

}

